name: Publish to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Generate Docs
              run: |
                  npm install
                  npm run build-docs

            - name: Publish generated content to GitHub Pages
              uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
              with:
                  dir: docs
                  branch: docs
                  token: ${{ secrets.ACCESS_TOKEN }}
